# permissions for end users to edit builds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: build-editor-role
rules:
- apiGroups:
  - operations.jahvon.dev
  resources:
  - builds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operations.jahvon.dev
  resources:
  - builds/status
  verbs:
  - get
